# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computes the empirical fluctuation process according to moving OLS estimates (type ME) 
#' @param X design matrix
#' @param y response vector
#' @param rescale boolean argument defining whether or not the estimates will be standardized
#' @param h bandwith of the process
#' @return square root of X
.sc_cpp_efp_process_me <- function(X, y, rescale, h) {
    .Call('strucchange_sc_cpp_efp_process_me', PACKAGE = 'strucchange', X, y, rescale, h)
}

#' Computes the empirical fluctuation process according to recursive OLS estimates (type RE) 
#' @param X design matrix
#' @param y response vector
#' @param rescale boolean argument defining whether or not the estimates will be standardized
#' @param h bandwith of the process
#' @return square root of X
.sc_cpp_efp_process_re <- function(X, y, rescale) {
    .Call('strucchange_sc_cpp_efp_process_re', PACKAGE = 'strucchange', X, y, rescale)
}

#' Computation of recursive residuals in C++
#' @param X design matrix
#' @param y response vector
#' @param start integer (1-based) index of the first observation to compute recursive residuals
#' @param end integer (1-based) index of the last observation to compute recursive residuals
#' @param tol tolerance in the computation of recursive model coefficients
#' @return vector containing the recursive residuals 
#' @seealso \code{\link{recresid}} and \code{\link{recresid.default}}
.sc_cpp_recresid <- function(X, y, start, end, tol) {
    .Call('strucchange_sc_cpp_recresid', PACKAGE = 'strucchange', X, y, start, end, tol)
}

#' Computes the square root of a symetric positive definite matrix
#' @param X symetric positive definite matrix
#' @return square root of X
.sc_cpp_rootmatrix <- function(X) {
    .Call('strucchange_sc_cpp_rootmatrix', PACKAGE = 'strucchange', X)
}

#' Computes the square root of the Gramian matrix t(X) %*% X
#' @param X a matrix
#' @return square root of t(X) %*% X
.sc_cpp_rootmatrix_cross <- function(X) {
    .Call('strucchange_sc_cpp_rootmatrix_cross', PACKAGE = 'strucchange', X)
}

