# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Computation of recursive residuals in C++
#' @param X design matrix
#' @param y response vector
#' @param start integer (1-based) index of the first observation to compute recursive residuals
#' @param end integer (1-based) index of the last observation to compute recursive residuals
#' @param tol tolerance in the computation of recursive model coefficients
#' @return vector containing the recursive residuals 
#' @seealso \code{\link{recresid}} and \code{\link{recresid.default}}
sc_cpp_recresid <- function(X, y, start, end, tol) {
    .Call('strucchange_sc_cpp_recresid', PACKAGE = 'strucchange', X, y, start, end, tol)
}

